"""V3 §5.3 market_regime_log repository — persist via DataPipeline 体例 (TB-2a foundation).

PURE function 模块: caller injects psycopg2 connection + manages commit/rollback (铁律 32).
0 LiteLLM / 0 Redis / 0 xtquant (铁律 31 Platform Engine PURE sustained).

DataPipeline 体例 (铁律 17): 用 execute_values 批量 INSERT 沿用 PR #43 / PR #45 例外条款 (LL-066)
— 本表写入是单 INSERT per call (1 row × 3 daily cadence), 故走 cursor.execute(...) 直接路径.
"""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import psycopg2.extensions

    from .interface import MarketRegime

logger = logging.getLogger(__name__)


def persist_market_regime(
    conn: psycopg2.extensions.connection,
    regime: MarketRegime,
) -> int:
    """Persist a MarketRegime to market_regime_log; return generated regime_id.

    Args:
        conn: psycopg2 connection (sync). Caller manages commit/rollback 边界
            per 铁律 32 (Service 不 commit).
        regime: MarketRegime instance to persist (frozen dataclass).

    Returns:
        regime_id (BIGSERIAL) generated by PG.

    Raises:
        psycopg2.Error: SQL execution failure (caller catches / rolls back).

    SQL pattern:
        INSERT INTO market_regime_log (timestamp, regime, confidence,
            bull_arguments, bear_arguments, judge_reasoning,
            market_indicators, cost_usd)
        VALUES (%s, %s, %s, %s::jsonb, %s::jsonb, %s, %s::jsonb, %s)
        RETURNING regime_id;

    Note: created_at omitted — DDL DEFAULT NOW() handles it (沿用 risk_metrics_daily
    + risk_event_log 体例; caller has no need to override audit timestamp).
    """
    sql = """
        INSERT INTO market_regime_log (
            timestamp, regime, confidence,
            bull_arguments, bear_arguments, judge_reasoning,
            market_indicators, cost_usd
        ) VALUES (
            %s, %s, %s,
            %s::jsonb, %s::jsonb, %s,
            %s::jsonb, %s
        )
        RETURNING regime_id
    """

    indicators_json: str
    if regime.indicators is not None:
        indicators_json = json.dumps(regime.indicators.to_jsonable())
    else:
        # 反 silent NULL: explicit empty object signals "indicators tracked but
        # unavailable" vs SQL NULL which signals "field unset" (different audit
        # semantics, sustained PR #320 case-mismatch lesson LL-157).
        indicators_json = "{}"

    bull_json = json.dumps(regime.bull_arguments_jsonable())
    bear_json = json.dumps(regime.bear_arguments_jsonable())

    cur = conn.cursor()
    try:
        cur.execute(
            sql,
            (
                regime.timestamp,
                regime.regime.value,  # Enum → str for SQL (CHECK constraint compatible)
                regime.confidence,
                bull_json,
                bear_json,
                regime.judge_reasoning,
                indicators_json,
                regime.cost_usd,
            ),
        )
        row = cur.fetchone()
        if row is None or row[0] is None:
            # 反 silent failure: RETURNING regime_id must produce a value (铁律 33).
            raise RuntimeError(
                "persist_market_regime: INSERT ... RETURNING regime_id returned NULL "
                "(unexpected per DDL BIGSERIAL — investigate DB state)"
            )
        regime_id = int(row[0])
        logger.info(
            "[market-regime] persisted regime_id=%d regime=%s confidence=%.4f ts=%s cost_usd=%.4f",
            regime_id,
            regime.regime.value,
            regime.confidence,
            regime.timestamp.isoformat(),
            regime.cost_usd,
        )
        return regime_id
    finally:
        cur.close()
