--- V3 §S7 L3 动态阈值 — dynamic_threshold_adjustments audit log (S7, 2026-05-11)
---
--- 用途: 记录每次 DynamicThresholdEngine 评估的阈值调整, 审计追溯.
---
--- 变更:
---   1. NEW TABLE dynamic_threshold_adjustments
---   2. TimescaleDB hypertable (chunk 1 day, 180 day retention)
---
--- Rollback: 2026_05_11_dynamic_threshold_adjustments_rollback.sql
---
--- 关联: V3 §6.4 / V3 §10 row 7 / 铁律 22

BEGIN;

CREATE TABLE IF NOT EXISTS dynamic_threshold_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    market_state TEXT NOT NULL CHECK (market_state IN ('calm', 'stress', 'crisis')),
    index_return NUMERIC(8, 6),
    limit_down_count INT,
    regime TEXT,
    rule_id TEXT NOT NULL,
    code TEXT NOT NULL,
    default_value NUMERIC(12, 6) NOT NULL,
    market_multiplier NUMERIC(6, 4) NOT NULL DEFAULT 1.0,
    stock_multiplier NUMERIC(6, 4) NOT NULL DEFAULT 1.0,
    effective_value NUMERIC(12, 6) NOT NULL,
    adjustment_reason TEXT,
    stock_metrics JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TimescaleDB hypertable (1-day chunks for audit granularity)
SELECT create_hypertable(
    'dynamic_threshold_adjustments', 'timestamp',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE
);

-- Index for query by rule+code within time range
CREATE INDEX IF NOT EXISTS idx_dta_rule_code_ts
    ON dynamic_threshold_adjustments (rule_id, code, timestamp DESC);

-- 180 day retention
SELECT add_retention_policy(
    'dynamic_threshold_adjustments', INTERVAL '180 days',
    if_not_exists => TRUE
);

COMMIT;

COMMENT ON TABLE dynamic_threshold_adjustments IS 'S7 L3 动态阈值调整审计日志 (V3 §6.4 §10 row 7)';
COMMENT ON COLUMN dynamic_threshold_adjustments.market_state IS 'Calm/Stress/Crisis (V3 §6.1)';
COMMENT ON COLUMN dynamic_threshold_adjustments.market_multiplier IS '市场级乘数 (1.0/0.8/0.5)';
COMMENT ON COLUMN dynamic_threshold_adjustments.stock_multiplier IS '个股级乘数 (ATR/beta/liquidity 综合)';
COMMENT ON COLUMN dynamic_threshold_adjustments.effective_value IS 'default * market * stock, L1 最终使用值';
