"""V3 §5.4 risk_memory repository — persist + retrieve via PG + pgvector (TB-3a).

PURE function module: caller injects psycopg2 connection + manages commit/rollback
(铁律 32). 0 LiteLLM / 0 BGE-M3 / 0 Redis — embedding computation 留 TB-3b
EmbeddingService; this module just persists pre-computed vector + serves cosine
similarity queries.

DataPipeline 体例 (铁律 17): single-row INSERT per call (sub-PR 7b.3 体例 + LL-066
例外 sustained — small per-event sediment, not batch).
"""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import psycopg2.extensions

    from .interface import RiskMemory, SimilarMemoryHit

logger = logging.getLogger(__name__)


def _embedding_to_pgvector_str(embedding: tuple[float, ...] | None) -> str | None:
    """Convert 1024-dim tuple → pgvector text literal `[v1, v2, ...]` OR None.

    pgvector accepts text-encoded vector literals via `::vector` cast at INSERT
    time. Cheaper than COPY for single-row INSERT.
    """
    if embedding is None:
        return None
    return "[" + ",".join(f"{x:.6f}" for x in embedding) + "]"


def persist_risk_memory(
    conn: psycopg2.extensions.connection,
    memory: RiskMemory,
) -> int:
    """Persist a RiskMemory row → risk_memory; return generated memory_id.

    Args:
        conn: psycopg2 connection (sync). Caller manages commit/rollback per 铁律 32.
        memory: RiskMemory instance (frozen). embedding may be None
            (pre-RiskReflectorAgent or BGE-M3 unavailable) — DDL allows NULL +
            ivfflat partial index excludes NULL rows.

    Returns:
        memory_id (BIGSERIAL) generated by PG.

    Raises:
        psycopg2.Error: SQL execution failure (caller catches / rolls back).
        RuntimeError: NULL memory_id post-RETURNING (defensive per 铁律 33).
    """
    from .interface import RiskMemoryError  # noqa: PLC0415

    sql = """
        INSERT INTO risk_memory (
            event_type, symbol_id, event_timestamp, context_snapshot,
            action_taken, outcome, lesson, embedding
        ) VALUES (
            %s, %s, %s, %s::jsonb,
            %s, %s::jsonb, %s, %s::vector
        )
        RETURNING memory_id
    """

    embedding_str = _embedding_to_pgvector_str(memory.embedding)
    context_json = json.dumps(memory.context_snapshot_jsonable())
    outcome_json = json.dumps(memory.outcome_jsonable()) if memory.outcome is not None else None
    action_taken_str = memory.action_taken.value if memory.action_taken is not None else None

    cur = conn.cursor()
    try:
        cur.execute(
            sql,
            (
                memory.event_type,
                memory.symbol_id,
                memory.event_timestamp,
                context_json,
                action_taken_str,
                outcome_json,
                memory.lesson,
                embedding_str,
            ),
        )
        row = cur.fetchone()
        if row is None or row[0] is None:
            raise RiskMemoryError(
                "persist_risk_memory: INSERT ... RETURNING memory_id returned NULL "
                "(unexpected per DDL BIGSERIAL — investigate DB state)"
            )
        memory_id = int(row[0])
        logger.info(
            "[risk-memory] persisted memory_id=%d event_type=%s symbol=%s "
            "ts=%s has_embedding=%s has_lesson=%s",
            memory_id,
            memory.event_type,
            memory.symbol_id or "(market-wide)",
            memory.event_timestamp.isoformat(),
            memory.embedding is not None,
            memory.lesson is not None,
        )
        return memory_id
    finally:
        cur.close()


def retrieve_similar(
    conn: psycopg2.extensions.connection,
    query_embedding: tuple[float, ...],
    k: int = 5,
    *,
    event_type: str | None = None,
    min_cosine_similarity: float | None = None,
) -> list[SimilarMemoryHit]:
    """Vector similarity retrieval — top-k cosine-similar past risk memories.

    Args:
        conn: psycopg2 connection (sync; read-only path).
        query_embedding: BGE-M3 1024-dim query vector (computed by caller via
            TB-3b EmbeddingService). Must be exact 1024-dim or DDL rejects cast.
        k: top-N results to return (default 5, sustained V3 §11.2 line 1228
            "类似情况 N 次" — N typically 3-10 for L1 push augmentation).
        event_type: optional event_type filter (e.g. "LimitDown") — narrows
            search to same-category memories using composite index.
        min_cosine_similarity: optional floor (e.g. 0.7) — discard low-relevance
            hits. None = return all top-k regardless of similarity.

    Returns:
        list[SimilarMemoryHit] sorted by cosine_similarity DESC (most similar first).
        Empty list when no risk_memory rows have embeddings yet (TB-3b pre-wire state).

    Raises:
        ValueError: query_embedding wrong dimension.
        psycopg2.Error: SQL failure.
    """
    from .interface import (  # noqa: PLC0415
        ActionTaken,
        RiskMemory,
        RiskMemoryOutcome,
        SimilarMemoryHit,
    )

    if len(query_embedding) != 1024:
        raise ValueError(
            f"query_embedding must be 1024-dim (BGE-M3 per ADR-064 D2), "
            f"got {len(query_embedding)} dim"
        )
    if k <= 0:
        raise ValueError(f"k must be > 0, got {k}")

    query_str = _embedding_to_pgvector_str(query_embedding)
    # Reviewer-fix (PR pending #339 MEDIUM 2): CTE binds 1024-dim vector once
    # (avoids double-passing ~8KB text payload — distance + ORDER BY share q.qvec).
    base_sql = """
        WITH q AS (SELECT %s::vector AS qvec)
        SELECT memory_id, event_type, symbol_id, event_timestamp,
               context_snapshot, action_taken, outcome, lesson, embedding,
               created_at,
               1 - (embedding <=> q.qvec) AS cosine_sim
          FROM risk_memory, q
         WHERE embedding IS NOT NULL
    """
    params: list[Any] = [query_str]
    if event_type is not None:
        base_sql += " AND event_type = %s"
        params.append(event_type)
    base_sql += " ORDER BY embedding <=> q.qvec LIMIT %s"
    params.append(k)

    hits: list[SimilarMemoryHit] = []
    cur = conn.cursor()
    try:
        cur.execute(base_sql, tuple(params))
        for row in cur.fetchall():
            (
                memory_id,
                ev_type,
                sym,
                ts,
                ctx,
                action,
                outcome_raw,
                lesson,
                _embedding_raw,
                created,
                cosine_sim,
            ) = row
            cosine_sim_f = float(cosine_sim)
            if min_cosine_similarity is not None and cosine_sim_f < min_cosine_similarity:
                continue

            # outcome JSONB → RiskMemoryOutcome
            outcome_obj: RiskMemoryOutcome | None = None
            if outcome_raw is not None:
                outcome_obj = RiskMemoryOutcome(
                    pnl_1d=outcome_raw.get("pnl_1d"),
                    pnl_5d=outcome_raw.get("pnl_5d"),
                    pnl_30d=outcome_raw.get("pnl_30d"),
                    retrospective_correctness=outcome_raw.get("retrospective_correctness"),
                )

            # action_taken str → ActionTaken Enum (or None)
            action_obj: ActionTaken | None = None
            if action is not None:
                try:
                    action_obj = ActionTaken(action)
                except ValueError:
                    # DB has out-of-vocab action_taken — log + treat as None.
                    # Defensive against schema drift; should not occur due to
                    # CHECK constraint, but reviewer suggested fail-loud is too
                    # aggressive for retrieve (only affects 1 hit, not full search).
                    logger.warning(
                        "[risk-memory] memory_id=%d has out-of-vocab "
                        "action_taken=%r; mapping to None",
                        memory_id,
                        action,
                    )

            # Reconstruct RiskMemory (note: embedding excluded — retrieved row
            # already matched, no need to round-trip the 1024-dim vector).
            memory = RiskMemory(
                event_type=ev_type,
                symbol_id=sym,
                event_timestamp=ts,
                context_snapshot=ctx if ctx is not None else {},
                action_taken=action_obj,
                outcome=outcome_obj,
                lesson=lesson,
                embedding=None,  # excluded — caller doesn't need it for use
                created_at=created,
                memory_id=int(memory_id),
            )
            hits.append(
                SimilarMemoryHit(
                    memory=memory,
                    cosine_similarity=cosine_sim_f,
                )
            )
        logger.info(
            "[risk-memory] retrieved %d similar memories (k=%d, event_type=%s, min_sim=%s)",
            len(hits),
            k,
            event_type or "(any)",
            min_cosine_similarity if min_cosine_similarity is not None else "(none)",
        )
        return hits
    finally:
        cur.close()
